name: 'Yaml File'
description: 'Greet someone and record the time'
inputs:
  path:  # id of input
    description: 'Path'
    required: true
    default: 'None'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
